name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 20.x]  # Ejecutar pruebas en Node.js 16.x y 20.x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Usar la versión v3 en lugar de v2

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Usar la versión v3 en lugar de v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build the app
        run: npm run build
